import json
import random
import sqlite3
from datetime import datetime, timedelta
import os

# Configuration
DB_FILE = os.path.join(os.path.dirname(__file__), 'daily-data', 'scams.db')
INDIA_MASTER = os.path.join(os.path.dirname(__file__), 'daily-data', 'india_scams.jsonl')
GLOBAL_MASTER = os.path.join(os.path.dirname(__file__), 'daily-data', 'global_scams.jsonl')

# Placeholder for LLM interaction (e.g., Groq/Gemini)
def invoke_llm_for_scam_generation(prompt):
    # In a real scenario, this would call an actual LLM API
    # For simulation, we'll generate a simple scam URL
    scam_templates = [
        "http://{bank}-verify-{rand_num}.in/login",
        "http://{brand}-reward-{rand_str}.com/claim",
        "https://{service}-update-{rand_char}.net/kyc",
        "http://free-{item}-{rand_int}.xyz/offer"
    ]
    banks = ['sbi', 'hdfc', 'icici', 'axis']
    brands = ['paytm', 'phonepe', 'amazon']
    services = ['aadhaar', 'pan', 'upi']
    items = ['iphone', 'cashback', 'lottery']

    template = random.choice(scam_templates)
    
    replacements = {
        '{bank}': random.choice(banks),
        '{brand}': random.choice(brands),
        '{service}': random.choice(services),
        '{item}': random.choice(items),
        '{rand_num}': str(random.randint(1000, 9999)),
        '{rand_str}': ''.join(random.choices('abcdefghijklmnopqrstuvwxyz0123456789', k=8)),
        '{rand_char}': ''.join(random.choices('abcdefghijklmnopqrstuvwxyz', k=5)),
        '{rand_int}': str(random.randint(100, 999))
    }

    generated_url = template
    for key, value in replacements.items():
        generated_url = generated_url.replace(key, value)
        
    return {
        "url": generated_url,
        "type": "Synthetic Phishing",
        "reason": "Generated by PulseAgent for training",
        "source": "PulseAgent War Games"
    }

def add_scam_to_db(scam_data):
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    try:
        region = 'global'
        if any(b in scam_data['url'].lower() for b in ['sbi', 'hdfc', 'icici', 'paytm', 'phonepe', '.in']):
            region = 'india'

        c.execute("INSERT OR IGNORE INTO scams (url, source, type, date_added, region) VALUES (?, ?, ?, ?, ?)",
                  (scam_data['url'], scam_data['source'], scam_data['type'], datetime.now().isoformat(), region))
        conn.commit()
        
        # Also add to JSONL for data pipeline
        file_path = INDIA_MASTER if region == 'india' else GLOBAL_MASTER
        with open(file_path, 'a', encoding='utf-8') as f:
            f.write(json.dumps({"url": scam_data['url'], "source": scam_data['source'], "type": scam_data['type'], "date_added": datetime.now().isoformat()}) + '\n')

        return True
    except Exception as e:
        print(f"Error adding scam to DB: {e}")
        return False
    finally:
        conn.close()

def run_war_games(num_scams=10):
    print(f"[{datetime.now()}] PulseAgent initiating War Games (generating {num_scams} synthetic scams)...")
    generated_count = 0
    for i in range(num_scams):
        prompt = f"Generate a highly convincing phishing scam URL targeting financial institutions in India, focusing on KYC updates or reward claims. Make it subtle but effective. (Attempt {i+1})"
        scam = invoke_llm_for_scam_generation(prompt)
        if scam and add_scam_to_db(scam):
            generated_count += 1
            print(f"  Generated and added: {scam['url']}")
        else:
            print(f"  Failed to generate/add scam for attempt {i+1}")
            
    print(f"✅ PulseAgent War Games complete. {generated_count} new synthetic scams generated and added for training.")
    return generated_count

if __name__ == '__main__':
    # Ensure the daily-data directory exists
    os.makedirs(os.path.dirname(DB_FILE), exist_ok=True)
    
    # Initialize the main scams database if it doesn't exist
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS scams 
                 (url TEXT PRIMARY KEY, source TEXT, type TEXT, date_added TEXT, region TEXT)''')
    conn.commit()
    conn.close()

    run_war_games(num_scams=20) # Generate 20 scams for testing
